modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
issueTrackerURL = ""

[[mods]]
modId = "guaniao"
version = "${file.jarVersion}"
displayName = "\u89c2\u9e1f"
logoFile = "guaniao_logo.png"
authors = "EdDYON"
description = '''
我去！哪来的鸟
'''

[[dependencies.guaniao]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.guaniao]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.guaniao]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4,)"
ordering = "AFTER"
side = "BOTH"
